version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: rosamsoe-postgres
    ports:
      - 6500:5432
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./app.env

  pgAdmin:
    image: dpage/pgadmin4
    container_name: rosamsoe-pgadmin
    env_file:
      - ./app.env
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  progresDB:
